# Generated by Django 4.2.7 on 2025-09-20 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_operations_count', models.IntegerField(default=0)),
                ('last_operation_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('compress', 'Compress PDF'), ('pdf_to_img', 'PDF to Image'), ('img_to_pdf', 'Image to PDF'), ('docx_to_pdf', 'DOCX to PDF'), ('extract_text', 'Extract Text'), ('watermark', 'Add Watermark'), ('rotate', 'Rotate Pages'), ('secure', 'Secure PDF'), ('unlock', 'Unlock PDF')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processing histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
