# Generated by Django 4.2.7 on 2025-09-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_files_processed',
            field=models.IntegerField(default=0),
        ),
    ]
