# Generated by Django 4.2.7 on 2025-09-22 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0004_userprofile_is_premium_anonymoususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='last_operation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
